# Generated by Django 3.1.7 on 2021-03-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptiveStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_copy', models.TextField()),
                ('vars_data_set', models.TextField()),
                ('sample_or_population_choice', models.CharField(choices=[('S', 'Sample'), ('P', 'Population')], max_length=2)),
                ('maximum_max', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('minimum_mib', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('range_R', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('size_n', models.IntegerField()),
                ('sum_z', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('mean_x_bar', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('median_x_tilda', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('mode_mode', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('std_dev_s', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('variabce_s2', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('first_quartile_pos', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('second_quartile_pos', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('third_quartile_pos', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('first_quartile', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('second_quartile_MR', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('third_quartile', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('inter_quartile_range_IQR', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('outliers', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('sum_of_squares_SS', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('mean_absolute', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('deviation_MAD', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('root_mean_square_RMS', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('std_error_of_mean_SEx_bar', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('skewness_y1', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('kurtosis_B2', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('kurtosis_excess', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('kurtosis_in_excel_and_sheets_α4', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('coefficient_of_variation_CV', models.DecimalField(decimal_places=8, max_digits=10000)),
                ('relative_standard_deviation_RSD', models.DecimalField(decimal_places=8, max_digits=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
